[project]
name = "product-advisor-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "addasuryateja", email = "suryateja1234adda@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.4.1",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
]

[project.scripts]
product-advisor-agent = "product_advisor_agent:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
